ci:
  skip:
    - renovate-config-validator  # exceeds pre-commit.ci size limit

exclude: |
  (?x)^(
    (.*/)?package-lock\.json|
    (.*/)?poetry\.lock
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: file-contents-sorter
        args: [--unique]
        files: |
          (?x)^(
            \.dockerignore|
            \.gitignore
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '4']
        exclude: |
          (?x)^(
            package\.json
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '2']
        files: |
          (?x)^(
            package\.json
          )$
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.3
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/ITProKyle/pre-commit-hook-yamlfmt
    rev: v0.4.0
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --offset, '2', --sequence, '4']
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-toc
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.31.6
    hooks:
      - id: renovate-config-validator
        exclude: |
          (?x)^(
            presets/automerge-manager\.json
          )$
        files: |
          (?x)^(
            (^|/).?renovate.json(?:rc)?(?:\.json5?)?|
            presets/.*\.json|
            default\.json
          )$
